// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/person.proto

package models // import "github.com/slomek/playground/cel/models"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_ce6de8a749b3daeb, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "mycodesmells.celgo.models.Person")
}

func init() { proto.RegisterFile("models/person.proto", fileDescriptor_person_ce6de8a749b3daeb) }

var fileDescriptor_person_ce6de8a749b3daeb = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x31, 0x0f, 0x82, 0x30,
	0x10, 0x85, 0x83, 0x28, 0xc6, 0x4e, 0xa6, 0x2e, 0x75, 0x23, 0x2e, 0xe2, 0xd2, 0x0e, 0xfe, 0x03,
	0x27, 0x47, 0xc3, 0xe8, 0x06, 0xe5, 0x52, 0x8d, 0x77, 0x3d, 0xd2, 0xc2, 0xd0, 0x7f, 0x6f, 0x2c,
	0x71, 0xfb, 0xde, 0xcb, 0x97, 0xbc, 0x27, 0x0e, 0xc4, 0x03, 0x60, 0x34, 0x23, 0x84, 0xc8, 0x5e,
	0x8f, 0x81, 0x27, 0x96, 0x47, 0x4a, 0x96, 0x07, 0x88, 0x04, 0x88, 0x51, 0x5b, 0x40, 0xc7, 0x7a,
	0xf1, 0x4e, 0x77, 0x51, 0x3d, 0xb2, 0x2a, 0xa5, 0x58, 0xfb, 0x8e, 0x40, 0x15, 0x75, 0xd1, 0xec,
	0xda, 0xcc, 0x52, 0x89, 0xad, 0xe5, 0xd9, 0x4f, 0x21, 0xa9, 0x55, 0xae, 0xff, 0x51, 0xee, 0x45,
	0xd9, 0x39, 0x50, 0x65, 0x5d, 0x34, 0x9b, 0xf6, 0x87, 0xb7, 0xcb, 0xf3, 0xec, 0xde, 0xd3, 0x6b,
	0xee, 0xb5, 0x65, 0x32, 0x11, 0x99, 0xe0, 0x63, 0x46, 0xec, 0x92, 0x0b, 0x3c, 0xfb, 0xc1, 0x58,
	0x40, 0xb3, 0x8c, 0xf6, 0x55, 0xbe, 0x75, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xab, 0xbb, 0xa8,
	0x11, 0xad, 0x00, 0x00, 0x00,
}
